module.exports = {
    welcomeMessage: "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nInvité par **[inviterTag]** ([inviteValidCount] invitation(s)).\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**.",
    welcomeMessageUnknow: "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nJe ne sais pas comment il a été invité.\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**.",
    welcomeMessageVanity: "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nIl nous a rejoint avec **l'url personnalisée** (`[vanityCode]` : [vanityUses] utilisation(s)).\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**.",
    welcomeMessageHimself: "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nIl s'est invité lui même.\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**.",
    welcomeEmbed: {
        "title": "Bienvenue sur [serverName]",
        "type": "rich",
        "description": "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nInvité par **[inviterTag]** ([inviteValidCount] invitation(s)).\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    welcomeEmbedUnknow: {
        "title": "Bienvenue sur [serverName]",
        "type": "rich",
        "description": "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nJe ne sais pas comment il a été invité.\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    welcomeEmbedVanity: {
        "title": "Bienvenue sur [serverName]",
        "type": "rich",
        "description": "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nIl nous a rejoint avec **l'url personnalisée** (`[vanityCode]` : [vanityUses] utilisation(s)).\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    welcomeEmbedHimself: {
        "title": "Bienvenue sur [serverName]",
        "type": "rich",
        "description": "**[memberTag]** vient de rejoindre le serveur !\nC'est la **[memberTotalJoin]** fois qu'il rejoint.\nIl s'est invité lui même.\nSon compte a été créé il y a **[createdAt]**.\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    levelupMessage: "[member] vient de passer **level [level]** !",
    levelupEmbed: {
        "title": "[memberTag]",
        "type": "rich",
        "description": "[member] vient de passer **level [level]** !",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    leaveMessage: "**[memberTag]** vient de quitter le serveur, il avait été invité par **[inviterTag]** il y a [memberJoinAt].",
    leaveMessageVanity: "**[memberTag]** vient de quitter le serveur, il avait rejoint avec **l'url personnalisée** il y a [memberJoinAt].",
    leaveMessageUnknow: "**[memberTag]** vient de quitter le serveur, je ne sais pas comment il avait été invité il y a [memberJoinAt].",
    leaveMessageHimself: "**[memberTag]** vient de quitter le serveur, il s'était invité lui même il y a [memberJoinAt].",
    leaveEmbed: {
        "title": "[memberTag] vient de quitter le serveur",
        "type": "rich",
        "description": "Il nous avait rejoint il y a [memberJoinAt]\nInvité par **[inviterTag]** ([inviteValidCount] invitation(s))\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    leaveEmbedVanity: {
        "title": "[memberTag] vient de quitter le serveur",
        "type": "rich",
        "description": "Il nous avait rejoint il y a [memberJoinAt]\nIl avait utilisé **l'url personnalisée**\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    leaveEmbedUnknow: {
        "title": "[memberTag] vient de quitter le serveur",
        "type": "rich",
        "description": "Il nous avait rejoint il y a [memberJoinAt]\nJe ne sais pas qui l'avait invité\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
    leaveEmbedHimself: {
        "title": "[memberTag] vient de quitter le serveur",
        "type": "rich",
        "description": "Il nous avait rejoint il y a [memberJoinAt]\nIl s'était invité lui même\nNous sommes maintenant **[serverMemberCount]**",
        "url": null,
        "timestamp": null,
        "color": 3447003,
        "fields": [],
        "thumbnail": null,
        "image": null,
        "author": null,
        "footer": null
    },
}